# Generated by Django 5.1.5 on 2025-01-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_remove_room_created_at_remove_room_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
