# Generated by Django 5.1.5 on 2025-01-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
